/**
 * THE NATIVE MODULE MUST NOT BE GITIGNORED.
 *
 * `.gitignore` had `android/` and `ios/` unanchored. A pattern without a leading slash
 * matches a directory of that name at ANY depth, so `android/` silently swallowed
 * `modules/reading-service/android/` — the whole Kotlin foreground service.
 *
 * Caught on 2026-09-19 in the seconds before the Slice 6 commit. Had it gone in, the commit
 * would have succeeded, the working tree would have kept building perfectly, and a clean
 * checkout would have had a module with no native code in it: no service, no heartbeat, and
 * the app back to a cached process at `oom_score_adj` 900. The one machine that had the code
 * would have been the only one that worked, and the failure would have surfaced as "the timer
 * dies in the background" weeks later.
 *
 * That is the same shape as silent-pass item 8 (the typeface and the splash were in the
 * config and in no build) and item 23 (the service was in the manifest and in no APK): a
 * thing that exists locally, is referenced correctly, and is not in the artefact.
 *
 * Textual, so it carries a positive control.
 *
 * Run with: npm test
 */

import assert from 'node:assert/strict'
import { existsSync, readFileSync } from 'node:fs'
import { join } from 'node:path'
import { test } from 'node:test'

const ROOT = process.cwd()

/** Files that must reach a clean checkout, or the foreground service does not exist there. */
const MUST_BE_TRACKED = [
  'modules/reading-service/package.json',
  'modules/reading-service/expo-module.config.json',
  'modules/reading-service/index.ts',
  'modules/reading-service/android/build.gradle',
  'modules/reading-service/android/src/main/AndroidManifest.xml',
  'modules/reading-service/android/src/main/java/expo/modules/readingservice/ReadingService.kt',
  'modules/reading-service/android/src/main/java/expo/modules/readingservice/ReadingServiceModule.kt',
]

function rules(source: string): string[] {
  return source
    .split('\n')
    .map((line) => line.trim())
    .filter((line) => line !== '' && !line.startsWith('#'))
}

/**
 * Whether a rule can match a path segment at any depth.
 *
 * git's rule: a pattern with no leading slash and no interior slash matches at every level.
 * `/android/` matches the repo root only.
 */
function matchesAtAnyDepth(rule: string, directory: string): boolean {
  const body = rule.replace(/\/$/, '')
  if (body.startsWith('/') || body.includes('/')) return false
  return body === directory
}

test('the native module actually exists where the build expects it', () => {
  for (const path of MUST_BE_TRACKED) {
    assert.ok(existsSync(join(ROOT, path)), `${path} is missing`)
  }
})

test('no ignore rule swallows a directory at any depth', () => {
  const ignored = rules(readFileSync(join(ROOT, '.gitignore'), 'utf8'))
  const swallowed = ignored.filter(
    (rule) => matchesAtAnyDepth(rule, 'android') || matchesAtAnyDepth(rule, 'ios'),
  )
  assert.deepEqual(
    swallowed,
    [],
    'An unanchored rule matches at every depth, so it hides ' +
      'modules/reading-service/android/ — the Kotlin foreground service — from every clean ' +
      `checkout. Anchor it to the repo root instead: ${swallowed.join(', ')}`,
  )
})

test('the prebuild output at the root is still ignored', () => {
  // The other direction: `android/` and `ios/` at the ROOT are generated by prebuild and
  // must never be committed, or a stale native project ships instead of a generated one.
  const ignored = rules(readFileSync(join(ROOT, '.gitignore'), 'utf8'))
  for (const wanted of ['/android/', '/ios/']) {
    assert.ok(
      ignored.includes(wanted),
      `${wanted} is no longer ignored. The prebuild output would be committed, which is how ` +
        'a week of font and splash changes ended up in the config and in no build.',
    )
  }
})

/** The positive control: the matcher must flag the exact rule that caused this. */
test('positive control: the unanchored rule is recognised as the bug', () => {
  assert.equal(matchesAtAnyDepth('android/', 'android'), true)
  assert.equal(matchesAtAnyDepth('android', 'android'), true)
  // ...and the anchored forms are not.
  assert.equal(matchesAtAnyDepth('/android/', 'android'), false)
  assert.equal(matchesAtAnyDepth('modules/*/android/', 'android'), false)
  // An unrelated rule is not a false positive.
  assert.equal(matchesAtAnyDepth('node_modules/', 'android'), false)
})
